from views.welcome_view import WelcomeView
from views.dashboard_view import DashboardView
from views.market_view import MarketView
from views.analytics_view import AnalyticsView
from views.history_view import HistoryView
from views.jornada_view import JornadaView
from views.clausulazo_view import ClausulazoView
from views.settings_view import SettingsView
from views.players_view import PlayersView
